IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    ClearAllActions()
    SmallWait(3)
    FadeToColor([30.0],0)
    Wait(2)
    ActionOverride("kpdomo01",MoveBetweenAreas("AR1306",[1003.873],10))
    ActionOverride("kpbutl01",DestroySelf())
    ActionOverride("kpmaid02",DestroySelf())
    ActionOverride("Priestyr",DestroySelf())
    ActionOverride("kpmaid01",DestroySelf())
    SmallWait(2)
    FadeFromColor([30.0],0)
    Wait(1)
    EndCutSceneMode()
END

